### ISSUE TITLE
Text generation webui won't install.

### ISSUE THREAD

**Issue by Turb0br0** [cocktailpeanut/text-generation-webui.pinokio#1]
This is the error I get. 

F:\\\\Pinokio\\\\ap\r\ni\\\\text-generation-webui.pinokio.git\\\\text-generation-webui\\\\installer_files\\\\co\r\nnda\\\\pkgs\\\\setuptools-68.0.0-py310haa95532_0.conda.  You probably need to delete\r\n and re-download or re-create this file.  Message was:\\n\\nfailed with error: [Er\r\nrno 2] No such file or directory: 'F:\\\\\\\\Pinokio\\\\\\\\a\r\npi\\\\\\\\text-generation-webui.pinokio.git\\\\\\\\text-generation-webui\\\\\\\\installer_fi\r\nles\\\\\\\\conda\\\\\\\\pkgs\\\\\\\\setuptools-68.0.0-py310haa95532_0\\\\\\\\Lib\\\\\\\\site-package\r\ns\\\\\\\\setuptools\\\\\\\\config\\\\\\\\_validate_pyproject\\\\\\\\__pycache__\\\\\\\\fastjsonschem\r\na_exceptions.cpython-310.pyc'\")\r\n\r\n \r\nConda environment creation failed. \r\nPress any key to continue . . .

I do believe a file is missing. I could be wrong as I'm not all that tech savvy. I hope this is all you need.

**Comment by HostileRespite** [comment]
I am also having a Conda issue of some kind.

**Comment by smanaton** [comment]
> This is the error I get.
> 
> F:\\Pinokio\\ap\r\ni\\text-generation-webui.pinokio.git\\text-generation-webui\\installer_files\\co\r\nnda\\pkgs\\setuptools-68.0.0-py310haa95532_0.conda. You probably need to delete\r\n and re-download or re-create this file. Message was:\n\nfailed with error: [Er\r\nrno 2] No such file or directory: 'F:\\\\Pinokio\\\\a\r\npi\\\\text-generation-webui.pinokio.git\\\\text-generation-webui\\\\installer_fi\r\nles\\\\conda\\\\pkgs\\\\setuptools-68.0.0-py310haa95532_0\\\\Lib\\\\site-package\r\ns\\\\setuptools\\\\config\\\\_validate_pyproject\\\\**pycache**\\\\fastjsonschem\r\na_exceptions.cpython-310.pyc'")\r\n\r\n \r\nConda environment creation failed. \r\nPress any key to continue . . .
> 
> I do believe a file is missing. I could be wrong as I'm not all that tech savvy. I hope this is all you need.

did you solve this? having the same issue

**Comment by xeroctation** [comment]
> This is the error I get.
> 
> F:\\Pinokio\\ap\r\ni\\text-generation-webui.pinokio.git\\text-generation-webui\\installer_files\\co\r\nnda\\pkgs\\setuptools-68.0.0-py310haa95532_0.conda. You probably need to delete\r\n and re-download or re-create this file. Message was:\n\nfailed with error: [Er\r\nrno 2] No such file or directory: 'F:\\\\Pinokio\\\\a\r\npi\\\\text-generation-webui.pinokio.git\\\\text-generation-webui\\\\installer_fi\r\nles\\\\conda\\\\pkgs\\\\setuptools-68.0.0-py310haa95532_0\\\\Lib\\\\site-package\r\ns\\\\setuptools\\\\config\\\\_validate_pyproject\\\\**pycache**\\\\fastjsonschem\r\na_exceptions.cpython-310.pyc'")\r\n\r\n \r\nConda environment creation failed. \r\nPress any key to continue . . .
> 
> I do believe a file is missing. I could be wrong as I'm not all that tech savvy. I hope this is all you need.

did anyone solve this problem? facing the same issue

**Comment by smanaton** [comment]
> 

i just used text-generation-webui own 1 click installer in the end and that worked for me.

**Comment by phantomghost2023** [comment]
Error: File not found: at new WindowsPtyAgent (C:\Users\PC\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\node-pty-prebuilt-multiarch-cp\lib\windowsPtyAgent.js:76:36) at new WindowsTerminal (C:\Users\PC\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\node-pty-prebuilt-multiarch-cp\lib\windowsTerminal.js:51:24) at Object.spawn (C:\Users\PC\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\node-pty-prebuilt-multiarch-cp\lib\index.js:29:12) at C:\Users\PC\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\pinokiod\kernel\shell.js:215:22 at new Promise () at Shell.prompt (C:\Users\PC\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\pinokiod\kernel\shell.js:199:12) at Shell.request (C:\Users\PC\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\pinokiod\kernel\shell.js:186:38) at async Shell.start (C:\Users\PC\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\pinokiod\kernel\shell.js:115:20) at async Shells.launch (C:\Users\PC\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\pinokiod\kernel\shells.js:129:20) at async Shells.run (C:\Users\PC\AppData\Local\Programs\Pinokio\re

**Comment by Crakxploit** [comment]
install perfectly but when start that ask you A,B,C for GPU no let me choose the option, before in the installation pop-up text box to choose but now not even that. I re-install pinokio and same problem, also the internet speed is really bad

**Comment by kiam001** [comment]
Same Problem cant choose GPU settings


![image](https://github.com/cocktailpeanut/text-generation-webui.pinokio/assets/10757700/f612a155-d983-4ea0-8f73-a0e5a2a2edad)

**Comment by xeroctation** [comment]
> Same Problem cant choose GPU settings
> 
> ![image](https://user-images.githubusercontent.com/10757700/272545005-f612a155-d983-4ea0-8f73-a0e5a2a2edad.png)

what do you mean you cant? just type the appropriate letter and press enter

**Comment by kiam001** [comment]
This is a read only Terminal, i cant enter any text input in it

**Comment by jacklurker** [comment]
Same. I can't select a GPU

**Comment by Kuchiriel** [comment]
Same.

![Image](https://github.com/user-attachments/assets/9ed93b32-2904-4fc8-9d72-398527c4cdbe)

**Comment by ghost** [comment]
@Kuchiriel Did you solve the problem?

**Comment by Kuchiriel** [comment]
> [@Kuchiriel](https://github.com/Kuchiriel) Did you solve the problem?

Kind of, I just waited a long time and it selected the but I got stuck in another error.

**Comment by Kuchiriel** [comment]
Still same issue...
